networks:
  dauth-redis-net:
    driver: bridge
  nginx-net:
    external: true

services:
  dodam-oauth:
    build:
      context: .
      dockerfile: Dockerfile
    image: teamb1nd/dodam-oauth:latest
    platform: linux/arm64
    ports:
      - "8003:8003"
    networks:
      - dodam-redis-net
      - nginx-net

  dodam-open-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: teamb1nd/dodam-open-api:latest
    platform: linux/arm64
    ports:
      - "8010:8010"
    networks:
      - nginx-net

  dauth-redis:
    image: redis:alpine
    port: "6379:6379"
    networks:
      - dodam-redis-net  
      - nginx-net