services:
  dgit:
    container_name: dgit-server
    image: teamb1nd/dgit:latest
    platform: linux/arm64
    ports:
      - "3586:8080" 
    depends_on:
      - dgit-mysql
    networks:
      - nginx-net
    restart: no

  dgit-mysql:
    container_name: dgit-mysql
    image: mysql:5.7
    ports:
      - "33307:3306"
    volumes:
      - dgit-mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: ${secrets.DGIT_MYSQL_USER}
      MYSQL_PASSWORD: ${secrets.DGIT_MYSQL_PASSWORD}
    networks:
      - dgit-net
      - nginx-net

networks:
  dgit-net:
    driver: bridge
  nginx-net:
    external: true

volumes:
  dgit-mysql-data: