version: '3.8'

networks:
  dodam-redis-net:
    driver: bridge
  nginx-net:
    external: true

services:
  dodamdodam:
    build:
      context: .
      dockerfile: Dockerfile
    image: teamb1nd/dodamdodam:latest
    platform: linux/arm64
    ports:
      - "33333:8080"
    networks:
      - dodam-redis-net
      - nginx-net

  token-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: teamb1nd/token-server:latest
    platform: linux/arm64
    ports:
      - "8003:8003"
    networks:
      - dodam-redis-net
      - nginx-net

  redis:
    container_name: dodam-redis
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - dodam-redis-net
      - nginx-net

  redis-slave-1:
    container_name: dodam-redis1
    image: redis:alpine
    command: redis-server --slaveof redis 6379
    ports:
      - "6479:6379"
    depends_on:
      - redis
    networks:
      - dodam-redis-net
      - nginx-net

  redis-slave-2:
    container_name: dodam-redis2
    image: redis:alpine
    command: redis-server --slaveof redis 6379
    ports:
      - "6579:6379"
    depends_on:
      - redis
    networks:
      - dodam-redis-net
      - nginx-net