version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    networks:
      - nginx-net

networks:
  nginx-net:
    external: true