services:
  nginx:
    container_name: nginx-server
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:      
      - /home/ubuntu/docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf

    networks:
      - nginx-net

networks:
  nginx-net:
    external: true