services:
  nginx:
    container_name: nginx-server
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - dodam:/var/lib/docker/volumes/dodam/_data

    networks:
      - nginx-net

volumes:
  dodam:
    external: true

networks:
  nginx-net:
    external: true