configs:
  - file_name: dauth-docker-compose.yml
    server:
      user: ${{ secrets.MAIN_EC2_USER }}
      host: ${{ secrets.MAIN_EC2_HOST }}
      key: ${{ secrets.MAIN_EC2_KEY }}

  - file_name: dgit-docker-compose.yml
    server:
      user: ${{ secrets.MAIN_EC2_USER }}
      host: ${{ secrets.MAIN_EC2_HOST }}
      key: ${{ secrets.MAIN_EC2_KEY }}

  - file_name: dodamdodam-docker-compose.yml
    server:
      user: ${{ secrets.MAIN_EC2_USER }}
      host: ${{ secrets.MAIN_EC2_HOST }}
      key: ${{ secrets.MAIN_EC2_KEY }}

  - file_name: nginx-docker-compose.yml
    server:
      user: ${{ secrets.MAIN_EC2_USER }}
      host: ${{ secrets.MAIN_EC2_HOST }}
      key: ${{ secrets.MAIN_EC2_KEY }}
