configs:
  - file_name: dauth-docker-compose.yml
    server:
      user: USER_PLACEHOLDER
      host: HOST_PLACEHOLDER
      key: KEY_PLACEHOLDER

  - file_name: dgit-docker-compose.yml
    server:
      user: USER_PLACEHOLDER
      host: HOST_PLACEHOLDER
      key: KEY_PLACEHOLDER

  - file_name: dodamdodam-docker-compose.yml
    server:
      user: USER_PLACEHOLDER
      host: HOST_PLACEHOLDER
      key: KEY_PLACEHOLDER

  - file_name: nginx-docker-compose.yml
    server:
      user: USER_PLACEHOLDER
      host: HOST_PLACEHOLDER
      key: KEY_PLACEHOLDER
