name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy Docker Compose Files to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Copy Docker Compose files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa \
          dauth-docker-compose.yml \
          dgit-docker-compose.yml \
          dodamdodam-docker-compose.yml \
          nginx-docker-compose.yml \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/docker/