name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up yq
        uses: chrisdickinson/setup-yq@latest

      - name: Deploy using script
        env: 
          MAIN_EC2_USER: ${{ secrets.MAIN_EC2_USER }}
          MAIN_EC2_HOST: ${{ secrets.MAIN_EC2_HOST }}
          MAIN_EC2_KEY: ${{ secrets.MAIN_EC2_KEY }}
        run: |
          chmod +x deploy.sh
          ./deploy.sh
