name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy Docker Compose Files to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y jq sshpass

    - name: Read Configs
      id: read_configs
      run: |
        configs=$(cat .deploy/config.yml | yq '.configs')
        echo "::set-output name=configs::$configs"

    - name: Deploy Files to Servers
      env:
        CONFIGS: ${{ steps.read_configs.outputs.configs }}
      run: |
        echo "$CONFIGS" | jq -c '.[]' | while read config; do
          FILE_NAME=$(echo "$config" | jq -r '.file_name')
          SERVER_USER=$(echo "$config" | jq -r '.server_user')
          SERVER_HOST=$(echo "$config" | jq -r '.server_host')
          SERVER_KEY=$(echo "$config" | jq -r '.server_key')

          echo "Deploying $FILE_NAME to $SERVER_USER@$SERVER_HOST"

          sshpass -p "$SERVER_KEY" scp -o StrictHostKeyChecking=no \
            "./$FILE_NAME" "$SERVER_USER@$SERVER_HOST:/home/$SERVER_USER/docker/"
        done
